# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: Maven_Project\target
    - run: cd /home
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
    - run: mvn clean package -D mvn.test.skip
    - name: Publish to Github Pages
    - run: mvn deploy
      env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          BUILD_ENV: 'github-actions'
    #- name: Run with Maven
    #- run: java -jar \target\ClinicaOdontologicaB-0.0.1-SNAPSHOT.jar

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
